name: loggerw
description: Small, easy to use and extensible fork of logger which prints beautiful logs and records them into your API of choice.
version: 1.0.1
repository: https://github.com/marcelofeitoza/logger

environment:
    sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
    test: ^1.16.8
    lints: ^2.0.1

platforms:
    android:
    ios:
    linux:
    macos:
    web:
    windows:
dependencies:
    http: ^0.13.6
